/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import controller.Controladora;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristian De Sousa
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    Controladora control;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        control = new Controladora(this);
        control.iniciaVentana(this, "src/images/logoLudik.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel1 = new javax.swing.JPanel();
        fondo_label = new javax.swing.JLabel();
        diseñar_label_btn = new javax.swing.JLabel();
        comprar_label_btn = new javax.swing.JLabel();
        misDiseños_label_btn = new javax.swing.JLabel();
        quienesSomos_label = new javax.swing.JLabel();
        contecto_label = new javax.swing.JLabel();
        encabezado_label = new javax.swing.JLabel();
        lineaInferior_label = new javax.swing.JLabel();
        salir_label_btn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPanel1.setBackground(new java.awt.Color(255, 255, 255));
        JPanel1.setMaximumSize(new java.awt.Dimension(1060, 640));
        JPanel1.setPreferredSize(new java.awt.Dimension(1060, 640));
        JPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo_VentanaPrincipal-transformed.png"))); // NOI18N
        JPanel1.add(fondo_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 270, -1, -1));

        diseñar_label_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton_diseñar-transformed.png"))); // NOI18N
        diseñar_label_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        diseñar_label_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                diseñar_label_btnMouseClicked(evt);
            }
        });
        JPanel1.add(diseñar_label_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, 69));

        comprar_label_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton_comprar-transformed.png"))); // NOI18N
        comprar_label_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comprar_label_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comprar_label_btnMouseClicked(evt);
            }
        });
        JPanel1.add(comprar_label_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 250, 71));

        misDiseños_label_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton_misDiseños.png"))); // NOI18N
        misDiseños_label_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        misDiseños_label_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                misDiseños_label_btnMouseClicked(evt);
            }
        });
        JPanel1.add(misDiseños_label_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 240, 69));

        quienesSomos_label.setFont(new java.awt.Font("Questrial", 0, 24)); // NOI18N
        quienesSomos_label.setForeground(new java.awt.Color(232, 246, 250));
        quienesSomos_label.setText("¿Quiénes somos?");
        quienesSomos_label.setToolTipText("");
        quienesSomos_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quienesSomos_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quienesSomos_labelMouseClicked(evt);
            }
        });
        JPanel1.add(quienesSomos_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 200, -1));

        contecto_label.setFont(new java.awt.Font("Questrial", 0, 24)); // NOI18N
        contecto_label.setForeground(new java.awt.Color(232, 246, 250));
        contecto_label.setText("Contacto");
        contecto_label.setToolTipText("");
        contecto_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contecto_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contecto_labelMouseClicked(evt);
            }
        });
        JPanel1.add(contecto_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 150, 110, 30));

        encabezado_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ludik_encabezado.png"))); // NOI18N
        JPanel1.add(encabezado_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        lineaInferior_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lineaInferior.png"))); // NOI18N
        JPanel1.add(lineaInferior_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 651, -1, 20));

        salir_label_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton_salir.png"))); // NOI18N
        salir_label_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir_label_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salir_label_btnMouseClicked(evt);
            }
        });
        JPanel1.add(salir_label_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, 230, -1));

        getContentPane().add(JPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -20, 1150, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diseñar_label_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_diseñar_label_btnMouseClicked
        VentanaDiseñar ventana = new VentanaDiseñar();
        control.activaVentana(ventana, this);
    }//GEN-LAST:event_diseñar_label_btnMouseClicked

    private void comprar_label_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comprar_label_btnMouseClicked
        VentanaComprar ventana = new VentanaComprar();
        control.activaVentana(ventana, this);
    }//GEN-LAST:event_comprar_label_btnMouseClicked

    private void misDiseños_label_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_misDiseños_label_btnMouseClicked
        VentanaMisDiseños ventana = new VentanaMisDiseños();
        control.activaVentana(ventana, this);
    }//GEN-LAST:event_misDiseños_label_btnMouseClicked

    private void salir_label_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salir_label_btnMouseClicked
        int confirmacion = JOptionPane.showOptionDialog(
            null, "¿Desea salir del sistema?", "::::...Confirmación...:::",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (confirmacion == 0){
            this.dispose();//elimina la ventana de la memoria y no continúa ejecutándose
        }
    }//GEN-LAST:event_salir_label_btnMouseClicked

    private void quienesSomos_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quienesSomos_labelMouseClicked
        VentanaMisDiseños ventana = new VentanaMisDiseños();
        control.activaVentana(ventana, this);
    }//GEN-LAST:event_quienesSomos_labelMouseClicked

    private void contecto_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contecto_labelMouseClicked
        VentanaMisDiseños ventana = new VentanaMisDiseños();
        control.activaVentana(ventana, this);
    }//GEN-LAST:event_contecto_labelMouseClicked

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel1;
    private javax.swing.JLabel comprar_label_btn;
    private javax.swing.JLabel contecto_label;
    private javax.swing.JLabel diseñar_label_btn;
    private javax.swing.JLabel encabezado_label;
    private javax.swing.JLabel fondo_label;
    private javax.swing.JLabel lineaInferior_label;
    private javax.swing.JLabel misDiseños_label_btn;
    private javax.swing.JLabel quienesSomos_label;
    private javax.swing.JLabel salir_label_btn;
    // End of variables declaration//GEN-END:variables
}
